### ISSUE TITLE
Hi, this connector is tested?

### ISSUE THREAD

**Issue by teratronik** [ekarachkovsky/rvconnector#2]
It's work? Cause i try to start this on my server and get : 
`PHP Fatal error:  require(): Failed opening required '' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/src/service/Connector.php on line 2`
it's normal, cause path /vendor is empty

**Comment by alexkuznetsov** [comment]
@teratronik , hi.
As i know, it  has been used in production.
Do you run `composer install`? After that, vendor will be with required libraries.
Some commands can be viewed [here](https://getcomposer.org/doc/03-cli.md#install)

**Comment by teratronik** [comment]
yes, i already understood how to use this.
i make `/var/www/html/src/composer.phar install`
and vendor was complete.

But now, when i start records.php, i got this : 
`PHP Notice:  Undefined index: id in /var/www/html/src/actions/records.php on line 5
File not found or no permissions to read file. Report to your system administrator`

In this file 5-th line is : 
`$id = $_GET['id']*1;`

Can you help me? I really want to test your product :-)

**Comment by ekarachkovsky** [comment]
hi, @teratronik! The only php script that you need to start is Connector.php. It listens asterisk's AGI in endless cycle, store call information in mysql database (db section in config.inc) and trigger vtiger's callbacks.
Scripts in actions dir must be called from vtiger. Script records.php expects record identificator and returns call record.

**Comment by teratronik** [comment]
oh, thanks! i will try this

**Comment by alexkuznetsov** [comment]
@ekarachkovsky , hi, it is a surprise to receive comments from so old issues))
Checked up issues statuses?)
